version: '3.9'
services:
  api:
    container_name: file-browser-api
    build:
      context: ./api
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
  ui:
    container_name: file-browser-ui
    depends_on:
      - api
    build:
      context: ./ui
      dockerfile: Dockerfile
    expose:
      - "4200"
    ports:
      - "4200:80"
